FROM python:3.11.4-slim-bullseye
WORKDIR /app

# RUN apt-get update \
#   && apt -y install gettext-base iputils-ping vim default-mysql-client python3-pymysql alembic \
#   && apt-get clean

RUN pip install --upgrade pip
RUN pip install pystalk

COPY producer/index.py /app/
RUN chmod +x /app/index.py

COPY Docker/producer_entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh