FROM python:3.11.4-slim-bullseye
WORKDIR /app

RUN pip install --upgrade pip
RUN pip install pystalk

COPY consumer/index.py /app/
RUN chmod +x /app/index.py

COPY Docker/consumer_entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
